/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 sphere.gltf
Author: deecube1 (https://sketchfab.com/deecube1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-sphere-a525fc48c1d245e2883241e344773aa4
Title: Abstract sphere
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/sphere.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="65feb8d5067b4128bde007edea05f073fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="S1" scale={0.1} position={[-0.423, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="S2" scale={0.5}>
                    <group name="S3" scale={0.3}>
                      <mesh name="S3__0" geometry={nodes.S3__0.geometry} material={materials.RootNode} />
                    </group>
                    <mesh name="S2__0" geometry={nodes.S2__0.geometry} material={materials.RootNode} />
                  </group>
                  <mesh name="S1__0" geometry={nodes.S1__0.geometry} material={materials.RootNode} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/sphere.gltf')
